#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # Current Defaults
    # ================
    # windows_leader = "s"
    # leader = "\\"

    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    statusline_display_mode = false

    bootstrap_before = "r35#before"
    bootstrap_after = "r35#after"
    disabled_plugins = [
      "github"
    ]


[[layers]]
# Autocomplete code within SpaceVim, fuzzy find the candidates from 
# multiple completion sources, expand snippet before cursor automatically
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30
default_shell = 'terminal'

[[layers]]
# This layers provides general version control feature for vim. It 
# should work with all VC backends such as Git, Mercurial, Bazaar, 
# SVN, etc…
name = 'VersionControl'

# [[layers]]
# # This layer provides GitHub integration for SpaceVim
# name = 'github'

[[layers]]
name = 'lang#javascript'

[[layers]]
name = 'lang#toml'

[[layers]]
name = 'lang#python'

[[layers]]
name = 'lang#markdown'

[[layers]]
name = 'lang#ruby'

[[layers]]
name = 'lang#vim'

[[layers]]
name = 'lang#sh'

[[layers]]
name = 'lang#dockerfile'

[[layers]]
name = 'lang#go'

[[layers]]
name = 'lang#rust'

[[layers]]
name = 'lang#typescript'

[[layers]]
name = 'lang#lsp'
filetypes = [
  "rust",
  "javascript",
  "python",
  "go",
  "typescript",
  "sh",
]

[[layers]]
# This layers adds extensive support for git
name = 'git'

[[layers]]
# This layers provide a heavily customized fzf centric work-flow
name = 'fzf'

[[layers]]
name = 'tmux'

[[layers]]
name = 'tags'


[[layers]]
# Syntax checking automatically within SpaceVim, display error on the sign column and statusline.
name = 'checkers'

[[layers]]
name = 'tools'

[[custom_plugins]]
name = "dag/vim-fish"

[[custom_plugins]]
name = "tomtom/tcomment_vim"

[[custom_plugins]]
name = "hashivim/vim-terraform"

[[custom_plugins]]
name = "vimwiki/vimwiki"

[[custom_plugins]]
name = "ntpeters/vim-better-whitespace"

[[custom_plugins]]
name = "martinda/Jenkinsfile-vim-syntax"

# [[custom_plugins]]
# name = "neoclide/coc.nvim"
